project_id = "yatadupadielakuenxui"

[functions.liam-memory]
verify_jwt = false

[functions.generate-memories]
verify_jwt = false

[functions.generate-tags]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.composio-connect]
verify_jwt = false

[functions.composio-callback]
verify_jwt = false

[functions.gmail-search]
verify_jwt = false

[functions.gmail-fetch-emails]
verify_jwt = false

[functions.email-automation-triggers]
verify_jwt = false

[functions.email-automation-webhook]
verify_jwt = false

[functions.google-photos-sync]
verify_jwt = false

[functions.instagram-sync]
verify_jwt = false

[functions.instagram-automation-poll]
verify_jwt = false

[functions.twitter-automation-poll]
verify_jwt = false

[functions.composio-disconnect]
verify_jwt = false

[functions.trello-automation-triggers]
verify_jwt = false

[functions.trello-automation-webhook]
verify_jwt = false

[functions.hubspot-automation-triggers]
verify_jwt = false

[functions.hubspot-automation-webhook]
verify_jwt = false

[functions.twitter-alpha-tracker]
verify_jwt = false

[functions.linkedin-connection-event]
verify_jwt = false

[functions.todoist-automation-triggers]
verify_jwt = false

[functions.fireflies-automation-triggers]
verify_jwt = false

[functions.fireflies-webhook]
verify_jwt = false

[functions.googledrive-automation-triggers]
verify_jwt = false

[functions.googledrive-webhook]
verify_jwt = false
