project_id = "ttanhgbtdyatzacxhxjj"

[functions.liam-memory]
verify_jwt = false

[functions.generate-memories]
verify_jwt = false

[functions.generate-tags]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false
