// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yatadupadielakuenxui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdGFkdXBhZGllbGFrdWVueHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1Nzg1NzksImV4cCI6MjA4NDE1NDU3OX0.G6MyJfGjhzfTVEzJA5OVSNY4c41oWGhDUf__mJ5-g9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});